# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('desc', models.TextField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
    ]
